# Generated by Django 5.1.3 on 2024-12-03 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_teache_name_978a13_idx'), models.Index(fields=['subject'], name='core_teache_subject_be0d97_idx')],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='core_studen_name_a58b91_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['dob'], name='core_studen_dob_7f5687_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_id'], name='core_studen_class_i_3516fa_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student_id'], name='core_grade_student_e3facc_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['subject_id'], name='core_grade_subject_83715e_idx'),
        ),
    ]
