# Generated by Django 5.1.3 on 2024-12-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['name'], name='core_class_name_d2e40d_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['teacher_id'], name='core_class_teacher_1eb107_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student_id'], name='core_grade_student_e3facc_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['subject_id'], name='core_grade_subject_83715e_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='core_studen_name_a58b91_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['dob'], name='core_studen_dob_7f5687_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_id'], name='core_studen_class_i_3516fa_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name'], name='core_subjec_name_36111e_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['name'], name='core_teache_name_978a13_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['subject'], name='core_teache_subject_be0d97_idx'),
        ),
    ]
